name: Deploy Swagger to Github Pages

on:
  push:

jobs:
  generate-swagger-ui:
    runs-on: ubuntu-latest
    steps:
        - name: Upload openapi.json
          uses: actions/upload-artifact@v3
          with:
            name: spec-file
            path: docs/oas/main.yml
        - name: Generate Swagger UI
          uses: Legion2/swagger-ui-action@v1
          with:
            output: swagger-ui
            spec-file: spec-file
  deploy:
    needs: generate-swagger-ui
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui