name: Deploy Swagger to Github Pages

on:
  push:

jobs:
  publish-swagger-ui:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Generate Swagger UI
          uses: Legion2/swagger-ui-action@v1
          with:
            output: swagger-ui
            spec-file: docs/oas/main.yml
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ./swagger-ui
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: publish-swagger-ui
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1